version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "type: dependencies"
    reviewers:
      - "honeycombio/collection-team"
    commit-message:
      prefix: "maint"
      include: "scope"
