version: 2.1

orbs:
  buildevents: honeycombio/buildevents@0.9.0

# enable a job when tag created (tag create is ignored by default)
filters_always: &filters_always
  filters:
    tags:
      only: /.*/

# restrict a job to only run when a version tag (vNNNN) is created
filters_publish: &filters_publish
  filters:
    tags:
      only: /^v[0-9].*/
    branches:
      ignore: /.*/

matrix_goversions: &matrix_goversions
  matrix:
    parameters:
      goversion: ["16", "17", "18", "19"]

# Default version of Go to use for Go steps
default_goversion: &default_goversion "18"

executors:
  go:
    parameters:
      goversion:
        type: string
        default: *default_goversion
    docker:
      - image: cimg/go:1.<< parameters.goversion >>
        environment:
          GO111MODULE: "on"
  github:
    docker:
      - image: cibuilds/github:0.13.0

jobs:
  setup:
    executor: go
    steps:
      - buildevents/start_trace
  watch:
    executor: go
    steps:
      - buildevents/watch_build_and_finish

  test:
    parameters:
      goversion:
        type: string
        default: *default_goversion
    executor:
      name: go
      goversion: "<< parameters.goversion >>"
    steps:
      - buildevents/with_job_span:
          steps:
            - checkout
            - run: make test
            - store_test_results:
                path: ./unit-tests.xml
            - buildevents/add_context:
                field_name: go_version
                field_value: << parameters.goversion >>

  publish_github:
    executor: github
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: "create draft release at GitHub"
          command: make publish_github

workflows:
  build:
    jobs:
      - setup:
          <<: *filters_always
      - watch:
          <<: *filters_always
          requires:
            - setup
      - test:
          <<: *matrix_goversions
          <<: *filters_always
          requires:
            - setup
      - publish_github:
          <<: *filters_publish
          context: Honeycomb Secrets for Public Repos
          requires:
            - setup
