version: 2.1

orbs:
  buildevents: honeycombio/buildevents@0.9.0

matrix_goversions: &matrix_goversions
  matrix:
    parameters:
      goversion: ["16", "17", "18", "19"]

# Default version of Go to use for Go steps
default_goversion: &default_goversion "18"

executors:
  go:
    parameters:
      goversion:
        type: string
        default: *default_goversion
    docker:
      - image: cimg/go:1.<< parameters.goversion >>
        environment:
          GO111MODULE: "on"

jobs:
  setup:
    executor: go
    steps:
      - buildevents/start_trace
  watch:
    executor: go
    steps:
      - buildevents/watch_build_and_finish

  test:
    parameters:
      goversion:
        type: string
        default: *default_goversion
    executor:
      name: go
      goversion: "<< parameters.goversion >>"
    steps:
      - buildevents/with_job_span:
          steps:
            - checkout
            - run: make test
            - store_test_results:
                path: ./unit-tests.xml
            - buildevents/add_context:
                field_name: go_version
                field_value: << parameters.goversion >>

workflows:
  test:
    jobs:
      - setup
      - watch:
          requires:
            - setup
      - test:
          <<: *matrix_goversions
          requires:
            - setup
