version: 2.1

# enable a job when tag created (tag create is ignored by default)
filters_always: &filters_always
  filters:
    tags:
      only: /.*/

# restrict a job to only run when a version tag (vNNNN) is created
filters_publish: &filters_publish
  filters:
    tags:
      only: /^v[0-9].*/
    branches:
      ignore: /.*/

matrix_goversions: &matrix_goversions
  matrix:
    parameters:
      goversion: ["16", "17", "18", "19"]

# Default version of Go to use for Go steps
default_goversion: &default_goversion "18"

executors:
  go:
    parameters:
      goversion:
        type: string
        default: *default_goversion
    docker:
      - image: cimg/go:1.<< parameters.goversion >>
        environment:
          GO111MODULE: "on"

jobs:
  test:
    parameters:
      goversion:
        type: string
        default: *default_goversion
    executor:
      name: go
      goversion: "<< parameters.goversion >>"
    steps:
      - checkout
      - run: make test
      - store_test_results:
          path: ./unit-tests.xml

  publish_github:
    executor: go
    steps:
      - checkout
      - run:
          name: Install ghr for drafting GitHub Releases
          command: go install github.com/tcnksm/ghr@latest
      - run:
          name: "create draft release at GitHub"
          command: make publish_github

workflows:
  build:
    jobs:
      - test:
          <<: *matrix_goversions
          <<: *filters_always
      - publish_github:
          <<: *filters_publish
          context: Honeycomb Secrets for Public Repos
          requires:
            - test
